export { default as Header } from './header'
export { default as Growth } from './growth'
export { default as Value } from './values'
export { default as Review } from './review'
export { default as About } from './about'
export { default as Banner } from './banner'
export { default as Community } from './community'
export { default as Product } from './product'
